In [1]:
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath("../utils"))
from functions import obtenerCardinalidad, clasificarVariables

In [2]:
df = pd.read_parquet("../data/chicago_definitivo.parquet")

In [3]:
df.head()

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,District,Ward,Community Area,Year,Latitude,Longitude,Location,neighborhood_name,unemployment_rate,hardship_index,median_income,people_of_color_pct,child_opportunity_index
0,10508693,2016-05-03,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,10.0,24.0,29,2016,41.864073,-87.706819,"(41.864073157, -87.706818608)",North Lawndale,20.642101,94.022550,33843.809645,95.448671,2.758848
1,10508695,2016-05-03,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,3.0,20.0,42,2016,41.782922,-8.760436,"(41.782921527, -87.60436317)",Woodlawn,16.621749,84.281178,33427.020339,91.581778,14.535765
2,10508697,2016-05-03,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,15.0,37.0,25,2016,41.894908,-87.758372,"(41.894908283, -87.758371958)",Austin,17.040736,85.105219,46440.558367,94.673310,5.768246
3,10508698,2016-05-03,BATTERY,SIMPLE,SIDEWALK,False,False,15.0,28.0,25,2016,41.885687,-87.749516,"(41.885686845, -87.749515983)",Austin,17.040736,85.105219,46440.558367,94.673310,5.768246
4,10508699,2016-05-03,THEFT,$500 AND UNDER,RESIDENCE,False,True,15.0,28.0,25,2016,41.886297,-87.761751,"(41.886297242, -87.761750709)",Austin,17.040736,85.105219,46440.558367,94.673310,5.768246

## Clasificación de variables

**Dataset1:** chicago_definitivo.parquet  

**Descripción:** Crímenes cometidos en la ciudad de Chicago (Illinois, USA), enriquecido con datos socioeconómicos por community area.  

**Periodo:** Del 1 de enero de 2014 a 31 de diciembre de 2016

| Nombre del campo | Descripción | Tipo de variable | Importancia inicial | Notas |
|---|---|---|---|---|
| ID | Identificador único del registro. | | | |
| Date | Fecha en que ocurrió el incidente. En ocasiones es una estimación aproximada. | | | |
| Primary Type | La descripción principal del código IUCR. | | | |
| Description | La descripción secundaria del código IUCR, una subcategoría de la descripción principal. | | | |
| Location Description | Descripción del lugar donde ocurrió el incidente. | | | |
| Arrest | Indica si se realizó una detención. | | | |
| Domestic | Indica si el incidente fue de carácter doméstico. | | | |
| District | Indica el distrito policial donde ocurrió el incidente. | | | |
| Ward | El concejo (distrito del Ayuntamiento) donde ocurrió el incidente. | | | |
| Community Area | Indica el área comunitaria donde ocurrió el incidente. Chicago tiene 77 áreas comunitarias. | | | |
| Year | Año en que ocurrió el incidente. | | | |
| Latitude | La latitud de la ubicación donde ocurrió el incidente. | | | |
| Longitude | La longitud de la ubicación donde ocurrió el incidente. | | | |
| Location | La ubicación donde ocurrió el incidente. | | | |
| neighborhood_name | Nombre del área comunitaria | | | |
| unemployment_rate | Porcentaje de desempleo en el área comunitaria | | | |
| hardship_index | Índice de calidad de vida | | | |
| median_income | Salario medio en el área comunitaria | | | |
| people_of_color_pct | Porcentaje de personas de color en el área comunitaria | | | |
| child_opportunity_index | Índice de oportunidades educativas para la infancia | | | |

In [5]:
df_clasificacion = clasificarVariables(df)
df_clasificacion

                           Card  Card_pct     Tipo   Clasificada_como
ID                       162448    100.00    int64  Numerica Continua
Date                        335      0.21      str  Numerica Discreta
Primary Type                 32      0.02      str  Numerica Discreta
Description                 299      0.18      str  Numerica Discreta
Location Description        106      0.07      str  Numerica Discreta
Arrest                        2      0.00     bool            Binaria
Domestic                      2      0.00     bool            Binaria
District                     23      0.01  float64  Numerica Discreta
Ward                         50      0.03  float64  Numerica Discreta
Community Area               77      0.05    int64  Numerica Discreta
Year                          3      0.00    int64         Categorica
Latitude                  94779     58.34  float64  Numerica Continua
Longitude                 94770     58.34  float64  Numerica Continua
Location                  94794     58.35      str  Numerica Continua
neighborhood_name            77      0.05      str  Numerica Discreta
unemployment_rate            77      0.05  float64  Numerica Discreta
hardship_index               77      0.05  float64  Numerica Discreta
median_income                77      0.05  float64  Numerica Discreta
people_of_color_pct          77      0.05  float64  Numerica Discreta
child_opportunity_index      77      0.05  float64  Numerica Discreta

| Nombre del campo | Descripción | Tipo de variable | Importancia inicial |
|---|---|---|---|
| ID | Identificador único del registro. | Índice único | - |
| Date | Fecha en que ocurrió el incidente. En ocasiones es una estimación aproximada. | Fecha | - |
| Primary Type | La descripción principal del código IUCR. | Numérica Discreta | 0 |
| Description | La descripción secundaria del código IUCR, una subcategoría de la descripción principal. | Numérica Discreta | 3 |
| Location Description | Descripción del lugar donde ocurrió el incidente. | Numérica Discreta | 3 |
| Arrest | Indica si se realizó una detención. | Binaria | 1 |
| Domestic | Indica si el incidente fue de carácter doméstico. | Binaria | 2 |
| District | Indica el distrito policial donde ocurrió el incidente. | Numérica Discreta | 3 |
| Ward | El concejo (distrito del Ayuntamiento) donde ocurrió el incidente. | Numérica Discreta | 3 |
| Community Area | Indica el área comunitaria donde ocurrió el incidente. Chicago tiene 77 áreas comunitarias. | Numérica Discreta | 3 |
| Year | Año en que ocurrió el incidente. | Categórica | 2 |
| Latitude | La latitud de la ubicación donde ocurrió el incidente. | Numérica Continua | 3 |
| Longitude | La longitud de la ubicación donde ocurrió el incidente. | Numérica Continua | 3 |
| Location | La ubicación donde ocurrió el incidente. | Numérica Continua | 2 |
| neighborhood_name | Nombre del área comunitaria | Categórica | 2 |
| unemployment_rate | Porcentaje de desempleo en el área comunitaria | Numérica Discreta | 1 |
| hardship_index | Índice de calidad de vida | Numérica Discreta | 1 |
| median_income | Salario medio en el área comunitaria | Numérica Discreta | 1 |
| people_of_color_pct | Porcentaje de personas de color en el área comunitaria | Numérica Discreta | 1 |
| child_opportunity_index | Índice de oportunidades educativas para la infancia | Numérica Discreta | 1 |

## Posiciones medias

In [6]:
df.describe().loc["mean"]

ID                         9.817199e+06
District                   1.119693e+01
Ward                       2.274919e+01
Community Area             3.767654e+01
Year                       2.014390e+03
Latitude                   4.190938e+01
Longitude                 -8.737932e+01
unemployment_rate          1.568892e+01
hardship_index             6.798591e+01
median_income              6.150110e+04
people_of_color_pct        7.749039e+01
child_opportunity_index    2.582258e+01
Name: mean, dtype: float64

In [7]:
df.describe().loc["50%"]

ID                         9.804126e+06
District                   1.000000e+01
Ward                       2.300000e+01
Community Area             3.200000e+01
Year                       2.014000e+03
Latitude                   4.183548e+01
Longitude                 -8.766035e+01
unemployment_rate          1.662175e+01
hardship_index             8.428118e+01
median_income              4.955403e+04
people_of_color_pct        9.158178e+01
child_opportunity_index    1.475901e+01
Name: 50%, dtype: float64

In [8]:
df.describe().loc["max"]

ID                         1.055035e+07
District                   3.100000e+01
Ward                       5.000000e+01
Community Area             7.700000e+01
Year                       2.016000e+03
Latitude                   4.202113e+02
Longitude                 -8.752685e+00
unemployment_rate          3.711521e+01
hardship_index             9.947184e+01
median_income              1.462735e+05
people_of_color_pct        9.916664e+01
child_opportunity_index    8.861183e+01
Name: max, dtype: float64

In [11]:
# lista de categóricas

categoricas = [
    'Year',
    'neighborhood_name',]

In [12]:
df[categoricas].mode().T

                        0
Year                 2014
neighborhood_name  Austin