In [10]:
import pandas as pd

In [11]:
df_chicago_crimes = pd.read_csv("../src/data/Chicago_Crimes_2014_to_2017.csv", sep=";")

In [12]:
df_chicago_data = pd.read_csv("../src/data/Chicago Health Atlas Data Download - Community areas.csv", sep=",")

In [13]:
df_chicago_crimes.head(5)

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,3,10508693,HZ250496,05/03/2016,013XX S SAWYER AVE,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,...,24.0,29.0,08B,1154907.0,1893681.0,2016,05/10/2016 15:56,41.864.073.157,-87.706.818.608,"(41.864073157, -87.706818608)"
1,89,10508695,HZ250409,05/03/2016,061XX S DREXEL AVE,486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,...,20.0,42.0,08B,1183066.0,1864330.0,2016,05/10/2016 15:56,41.782.921.527,-8.760.436.317,"(41.782921527, -87.60436317)"
2,197,10508697,HZ250503,05/03/2016,053XX W CHICAGO AVE,470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,...,37.0,25.0,24,1140789.0,1904819.0,2016,05/10/2016 15:56,41.894.908.283,-87.758.371.958,"(41.894908283, -87.758371958)"
3,673,10508698,HZ250424,05/03/2016,049XX W FULTON ST,460,BATTERY,SIMPLE,SIDEWALK,False,...,28.0,25.0,08B,1143223.0,1901475.0,2016,05/10/2016 15:56,41.885.686.845,-87.749.515.983,"(41.885686845, -87.749515983)"
4,911,10508699,HZ250455,05/03/2016,003XX N LOTUS AVE,820,THEFT,$500 AND UNDER,RESIDENCE,False,...,28.0,25.0,6,1139890.0,1901675.0,2016,05/10/2016 15:56,41.886.297.242,-87.761.750.709,"(41.886297242, -87.761750709)"

In [14]:
df_chicago_crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408122 entries, 0 to 408121
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            408122 non-null  int64
 1   ID                    408122 non-null  int64
 2   Case Number           408122 non-null  object
 3   Date                  408122 non-null  object
 4   Block                 408122 non-null  object
 5   IUCR                  408122 non-null  object
 6   Primary Type          408122 non-null  object
 7   Description           408122 non-null  object
 8   Location Description  407855 non-null  object
 9   Arrest                408122 non-null  bool
 10  Domestic              408122 non-null  bool
 11  Beat                  408122 non-null  int64
 12  District              408122 non-null  float64
 13  Ward                  408119 non-null  float64
 14  Community Area        408121 non-null  float64
 15  FBI Code              408122 non-null  object
 16  X Coordinate          401894 non-null  float64
 17  Y Coordinate          401894 non-null  float64
 18  Year                  408122 non-null  int64
 19  Updated On            408122 non-null  object
 20  Latitude              401894 non-null  object
 21  Longitude             401894 non-null  object
 22  Location              401894 non-null  object
dtypes: bool(2), float64(5), int64(4), object(12)
memory usage: 66.2+ MB

In [15]:
df_chicago_crimes.isna().mean() * 100

Unnamed: 0              0.000000
ID                      0.000000
Case Number             0.000000
Date                    0.000000
Block                   0.000000
IUCR                    0.000000
Primary Type            0.000000
Description             0.000000
Location Description    0.065422
Arrest                  0.000000
Domestic                0.000000
Beat                    0.000000
District                0.000000
Ward                    0.000735
Community Area          0.000245
FBI Code                0.000000
X Coordinate            1.526014
Y Coordinate            1.526014
Year                    0.000000
Updated On              0.000000
Latitude                1.526014
Longitude               1.526014
Location                1.526014
dtype: float64

In [16]:
df_chicago_data.head(5)

,Layer,Name,GEOID,UMP_2012-2016,HDX_2012-2016,INC_2012-2016,POC_2016-2020,CHALYRO_2016
0,NaN,NaN,NaN,"Unemployment rate (%), 2012-2016","Hardship Index (score), 2012-2016","Median household income, 2012-2016","People of color (% of residents), 2016-2020","Child Opportunity Index 3.0 (ED), 2016"
1,Community area,Rogers Park,1.0,8.504513572877206,62.972504962864825,49554.028565890825,55.04637728164608,34.654442144
2,Community area,Norwood Park,10.0,5.4095813548225715,25.48356985322108,97173.95208879767,22.00444625911391,57.010877998
3,Community area,Jefferson Park,11.0,7.503843108237212,38.28131134308272,84758.01159705805,41.73794882728365,50.24741268
4,Community area,Forest Glen,12.0,4.552057997239468,17.079266817084157,146273.52831758704,25.966173701075668,78.559728497